---
kind: pipeline
type: docker
name: kaniko-build-publish

platform:
  os: linux
  arch: amd64

steps:
- name: kaniko-build-publish
  pull: always
  image: plugins/kaniko:1.4.4-linux-amd64-kaniko1.8.0
  settings:
    dockerfile: Dockerfile
    context: .
    args:
      - BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
      - VCS_REF=${DRONE_COMMIT_SHA:0:7}
    tags:
      - linux-amd64
      - ${DRONE_COMMIT_SHA:0:8}
    registry: git.dotya.ml
    repo: wanderer/alpine-rsync
    username:
      from_secret: username
    password:
      from_secret: token
  when:
    ref:
      - refs/heads/master
    event:
      exclude: [pull_request, tag]
      include: [push, cron]

---
kind: pipeline
type: docker
name: notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: discord
  pull: always
  image: appleboy/drone-discord:latest
  settings:
    message: >
      {{#success build.status}}
        ✅ [Build #{{build.number}}]({{build.link}}) of `{{repo.name}}` succeeded.
        event: **`{{build.event}}`**
        commit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}`
        ```{{commit.message}}```
      {{else}}
        ❌ [Build #{{build.number}}]({{build.link}}) of `{{repo.name}}` failed.
        event: **`${DRONE_BUILD_EVENT}`**
        commit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}`
        ```{{commit.message}}```
      {{/success}}
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token

trigger:
  branch:
  - master
  event:
  - push
  status:
  - success
  - failure

depends_on:
- kaniko-build-publish

---
kind: pipeline
type: docker
name: notifications-cronbuild

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: discord
  pull: always
  image: appleboy/drone-discord:latest
  settings:
    message: >
      {{#success build.status}}
        ✅ [Nightly build #{{build.number}}]({{build.link}}) of `{{repo.name}}` succeeded.
        event: **`{{build.event}}`**
        commit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}`
      {{else}}
        ❌ [Nightly build #{{build.number}}]({{build.link}}) of `{{repo.name}}` failed.
        event: **`${DRONE_BUILD_EVENT}`**
        commit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}`
      {{/success}}
    webhook_id:
      from_secret: discord_webhook_hourly_id
    webhook_token:
      from_secret: discord_webhook_hourly_token
    username: drone-nightly

trigger:
  event:
  - cron
  cron:
  - nightly
  status:
  - success
  - failure

depends_on:
- kaniko-build-publish
